let model;let selectedFloor='all';const keys=new Set();const routeGroups=new Map();let routes=[];
const $=s=>document.querySelector(s);
const views={overall:[[520,390,580],[10,9,12],true],front:[[30,65,360],[22,19,45],true],airside:[[-270,125,-360],[20,16,0],true],end:[[292,75,66],[65,17,54],true],cutaway:[[160,220,275],[22,8,38],false],hall:[[-83,8,91],[-57,9,66],true],security:[[-8,38,76],[-10,12,39],false],gallery:[[-190,13.8,5],[-245,14,5],true],arrival:[[-74,2.1,71],[-40,2,49],true],arrivalvoid:[[-70,24,39],[-33,7,22],false]};
function setCamera(position,target){controls.enableDamping=false;camera.position.set(...position);controls.target.set(...target);controls.update();controls.enableDamping=true;}
function setFloor(floor,move=true){selectedFloor=String(floor);const bands={'1':[-.15,5.75,.3],'2':[5.85,11.65,6.3],'3':[11.65,50,12.1]};renderer.clippingPlanes=[];if(floor!=='all'){const [low,high,y]=bands[floor];renderer.clippingPlanes=[new THREE.Plane(new THREE.Vector3(0,1,0),-low),new THREE.Plane(new THREE.Vector3(0,-1,0),high)];$('#roof').checked=false;if(move)setCamera([22,y+195,58],[22,y,57.99]);}document.querySelectorAll('[data-floor]').forEach(b=>{b.classList.toggle('active',b.dataset.floor===selectedFloor);b.setAttribute('aria-pressed',String(b.dataset.floor===selectedFloor))});updateLayers();}
function setView(name){const v=views[name]||views.overall;$('#view').value=views[name]?name:'overall';setFloor('all',false);$('#roof').checked=v[2];$('#rotate').checked=false;controls.autoRotate=false;setCamera(v[0],v[1]);updateLayers();}
function updateLayers(){model?.traverse(o=>{if(!o.isMesh)return;const n=o.name;o.visible=!n.startsWith('Audit_')&&(!n.startsWith('Roof_')||$('#roof').checked)&&(!n.startsWith('Site_')||$('#site').checked)&&(!n.startsWith('Interior_')||$('#interior').checked)});}
function addRoute(data,index){const group=new THREE.Group();group.name=data.id;group.visible=false;const mat=new THREE.MeshBasicMaterial({color:data.color,depthTest:false,depthWrite:false,transparent:true,opacity:.92});const pts=data.points.map(p=>new THREE.Vector3(p[0],p[1]+index*.06,p[2]));for(let i=1;i<pts.length;i++){const delta=pts[i].clone().sub(pts[i-1]);const length=delta.length();if(length<.02)continue;const bar=new THREE.Mesh(new THREE.CylinderGeometry(.13,.13,length,6),mat);bar.position.copy(pts[i-1]).add(pts[i]).multiplyScalar(.5);bar.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.clone().normalize());bar.renderOrder=20+index;group.add(bar);if(length>5){for(let d=length*.55;d<length;d+=14){const arrow=new THREE.Mesh(new THREE.ConeGeometry(.5,1.3,8),mat);arrow.position.copy(pts[i-1]).lerp(pts[i],d/length);arrow.quaternion.copy(bar.quaternion);arrow.renderOrder=25+index;group.add(arrow)}}}for(const stop of data.stops){const ring=new THREE.Mesh(new THREE.TorusGeometry(.65,.12,6,16),mat);ring.rotation.x=Math.PI/2;ring.position.set(stop.position[0],stop.position[1]+.08,stop.position[2]);ring.renderOrder=30+index;group.add(ring);}scene.add(group);routeGroups.set(data.id,group);const label=document.createElement('label');label.className='route-option';label.style.setProperty('--route-color',data.color);label.innerHTML=`<input type="checkbox" data-route="${data.id}"><span class="swatch"></span><span>${data.label}</span>`;$('#route-list').append(label);label.querySelector('input').addEventListener('change',e=>{group.visible=e.target.checked;if(group.visible){$('#roof').checked=false;updateLayers();$('#route-stages').textContent=data.label+'：'+data.stops.map(s=>s.label).filter((v,i,a)=>i===0||v!==a[i-1]).join(' → ')}updateRouteButtons();});}
function updateRouteButtons(){const any=[...routeGroups.values()].some(g=>g.visible);$('#route-focus').disabled=!any;$('#route-clear').disabled=!any;if(!any)$('#route-stages').textContent='';}
function focusRoutes(){const points=routes.filter(r=>routeGroups.get(r.id)?.visible).flatMap(r=>r.points);if(!points.length)return;setFloor('all',false);$('#roof').checked=false;updateLayers();const box=new THREE.Box3().setFromPoints(points.map(p=>new THREE.Vector3(...p)));const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());const distance=Math.max(105,Math.max(size.x,size.z)*1.65);setCamera([center.x+distance*.18,center.y+distance*.95,center.z+distance*.8],center.toArray());$('#rotate').checked=false;controls.autoRotate=false;}
$('#view').addEventListener('change',e=>setView(e.target.value));document.querySelectorAll('[data-floor]').forEach(b=>b.addEventListener('click',()=>setFloor(b.dataset.floor)));for(const id of ['roof','site','interior'])$('#'+id).addEventListener('change',updateLayers);$('#rotate').addEventListener('change',e=>controls.autoRotate=e.target.checked);$('#route-focus').addEventListener('click',focusRoutes);$('#route-clear').addEventListener('click',()=>{routeGroups.forEach(g=>g.visible=false);document.querySelectorAll('[data-route]').forEach(c=>c.checked=false);updateRouteButtons()});$('#speed').addEventListener('input',e=>$('#speed-value').value=e.target.value+' m/s');$('#panel-toggle').addEventListener('click',()=>{const hidden=!$('#panel').hidden;$('#panel').hidden=hidden;$('#panel-toggle').textContent=hidden?'显示面板':'收起面板';$('#panel-toggle').setAttribute('aria-expanded',String(!hidden))});
new GLTFLoader().load('./assets/xiamen-gaoqi-t3.glb',g=>{model=g.scene;model.traverse(o=>{if(o.isMesh){o.castShadow=!o.material.transparent;o.receiveShadow=true;if(o.material.transparent)o.material.depthWrite=false}});scene.add(model);setView(new URLSearchParams(location.search).get('view')||'overall');$('#loading').hidden=true;window.modelReady=true;},undefined,e=>{$('#loading').textContent='模型加载失败，请刷新重试。';console.error(e)});
fetch('./assets/routes.json').then(r=>{if(!r.ok)throw Error('routes '+r.status);return r.json()}).then(data=>{routes=data;data.forEach(addRoute);window.routesReady=true}).catch(e=>{$('#route-error').hidden=false;$('#route-error').textContent='动线加载失败，请刷新重试。';console.error(e)});
let movementTime=performance.now();
function advanceMovement(now=performance.now()){
 const dt=Math.min((now-movementTime)/1000,1.5);movementTime=now;if(!keys.size)return;
 const forward=new THREE.Vector3();camera.getWorldDirection(forward);forward.y=0;if(forward.lengthSq()<.001)forward.set(0,0,-1);forward.normalize();
 const right=new THREE.Vector3().crossVectors(forward,camera.up),move=new THREE.Vector3();
 if(keys.has('w'))move.add(forward);if(keys.has('s'))move.sub(forward);if(keys.has('d'))move.add(right);if(keys.has('a'))move.sub(right);if(keys.has('q'))move.y-=1;if(keys.has('e'))move.y+=1;
 if(move.lengthSq())move.normalize().multiplyScalar(dt*Number($('#speed').value)*(keys.has('shift')?3:1));camera.position.add(move);controls.target.add(move);
}
addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea,button'))return;const k=e.key.toLowerCase();if(['w','a','s','d','q','e','shift'].includes(k)){advanceMovement();keys.add(k);e.preventDefault()}});
addEventListener('keyup',e=>{advanceMovement();keys.delete(e.key.toLowerCase())});
addEventListener('blur',()=>{keys.clear();movementTime=performance.now()});document.addEventListener('visibilitychange',()=>{keys.clear();movementTime=performance.now()});
renderer.domElement.tabIndex=0;renderer.domElement.addEventListener('pointerdown',()=>renderer.domElement.focus());
function frame(){requestAnimationFrame(frame);advanceMovement();controls.update();renderer.render(scene,camera)}frame();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
window.viewer={setView,setFloor,focusRoutes,routeGroups,camera,controls,scene,get model(){return model},get routes(){return routes}};
